package com.cts.plugin.loc.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.stereotype.Component;

import java.util.List;

@Configuration
@Component
public class OpenApiConfig {

    @Bean
    public OpenAPI genAiLocOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("GenAI LOC Tracker API")
                        .description("RESTful backend service for GenAI LOC Tracker — " +
                                "stores and queries Lines-of-Code events generated by " +
                                "GitHub Copilot / AI tools in IntelliJ IDEA.")
                        .version("1.0.0")
                        .contact(new Contact()
                                .name("CTS Plugin Team")
                                .email("plugin-support@cts.com"))
                        .license(new License()
                                .name("Internal Use Only")))
                .servers(List.of(
                        new Server()
                                .url("/api/v1")
                                .description("Default server")
                ));
    }
}

